In [ ]:
import pandas as pd

In [4]:
# Podemos utilizar el read_csv para leer archivos CSV de acceso público en internet
# En este caso dejé el archivo en AWS, para que sea de libre acceso. 

df = pd.read_csv("https://mysiterobert.s3.us-east-1.amazonaws.com/Dataframes/personas_clean.csv")
df.head(2)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,nombre_clean
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.0,Ambato,28/03/2023,Secundaria,NaN,Paola Mera Rodriguez
1,1829202652,isabela molina silva,39.0,167.8,166.2,M,480.0,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,Isabela Molina Silva

PRIMERTO: Convertir la fecha en formato fecha (Paso pendiente)

In [ ]:
#hint: vamos a utilizar la función pd.to_datetime()

In [8]:
df[ (df["sexo"] == "F") & (df["edad"]>30)]

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,nombre_clean
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.00,Ambato,28/03/2023,Secundaria,NaN,Paola Mera Rodriguez
3,1823588783,gustavo molina mera,39.0,169.4,166.7,F,826.56,Ambato,06/03/2025,Secundaria,NaN,Gustavo Molina Mera
6,1817361916,GABRIELA SILVA ESPINOZA,46.0,157.4,108.3,F,635.22,Ambato,2026-01-01,Secundaria,NaN,Gabriela Silva Espinoza
10,1828698470,David Loor Rodriguez,34.0,167.6,130.7,F,1168.12,Ambato,2024-05-27,Tecnico,david.loor.rodriguez@empresa.ec,David Loor Rodriguez
14,1856284441,Gustavo Sanchez Molina,53.0,171.1,165.0,F,696.58,Ambato,10/01/2023,Tecnico,gustavo.sanchez.molina@yahoo.com,Gustavo Sanchez Molina
...,...,...,...,...,...,...,...,...,...,...,...,...
53880,2321052629,andrés ortega suárez,47.0,162.6,118.9,F,480.00,Santo Domingo,2023-08-20,Tecnico,NaN,Andrés Ortega Suárez
53883,2318612724,Kevin Solís Sanchez,38.0,165.4,122.0,F,743.87,Santo Domingo,27/01/2025,Maestria,NaN,Kevin Solís Sanchez
53884,2347813244,Nicole Cedeño Chávez,32.0,156.6,116.4,F,572.92,Santo Domingo,2025-04-03,Maestria,nicole.cedeno.chavez@outlook.com,Nicole Cedeño Chávez
53885,2313772077,Alejandro Romero Suárez,35.0,171.2,133.9,F,1122.27,Santo Domingo,18/01/2025,Maestria,alejandro.romero.suarez@yahoo.com,Alejandro Romero Suárez
53893,2343577132,Andrés Silva García,41.0,162.1,149.0,F,720.60,Santo Domingo,09/12/2024,Secundaria,andres.silva.garcia@outlook.com,Andrés Silva García

In [ ]:
breakpoindf[(df["ciudad"] == "Quito") 
   | (df["ciudad"] == "Guayaquil") 
   | (df["ciudad"]=="Cuenca")]

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,nombre_clean
2594,157646670,Sebastián Loor Romero,34.0,164.8,147.3,F,736.24,Cuenca,2024-04-28,Universidad,sebastian.loor.romero@yahoo.com,Sebastián Loor Romero
2595,136450210,DIANA CEDEÑO VALENCIA,37.0,158.3,130.8,M,870.97,Cuenca,2024-07-21,Universidad,diana.cedeno.valencia@empresa.ec,Diana Cedeño Valencia
2596,130988827,Fernanda Herrera Quintero,38.0,174.2,163.0,M,480.00,Cuenca,2025-07-07,Universidad,fernanda.herrera.quintero@yahoo.com,Fernanda Herrera Quintero
2597,112860549,ALEJANDRA SILVA QUINTERO,38.0,157.6,143.6,M,766.22,Cuenca,2023-03-12,Universidad,NaN,Alejandra Silva Quintero
2598,115694457001,Elena Tapia Espinoza,53.0,155.3,112.6,F,886.04,Cuenca,28/11/2023,Universidad,elena.tapia.espinoza@gmail.com,Elena Tapia Espinoza
...,...,...,...,...,...,...,...,...,...,...,...,...
50242,1714751730,Andrés Vera Solís,45.0,178.8,166.2,F,899.26,Quito,2023-10-24,Secundaria,NaN,Andrés Vera Solís
50243,1711139111,Gustavo Loor Sanchez,25.0,165.0,159.8,M,1858.30,Quito,NaN,Maestria,NaN,Gustavo Loor Sanchez
50244,1731070429001,gustavo quintero alvarado,35.0,175.3,174.0,M,1823.65,Quito,"Oct 29, 2024",Maestria,NaN,Gustavo Quintero Alvarado
50245,1719423194,vanessa romero mera,40.0,166.7,139.2,F,533.18,Quito,25/05/2025,Secundaria,vanessa.romero.mera@hotmail.com,Vanessa Romero Mera
50246,1731578199,MIGUEL CORNEJO ROMERO,29.0,168.8,118.2,F,811.75,Quito,04/06/2023,Universidad,miguel.cornejo.romero@empresa.ec,Miguel Cornejo Romero

In [45]:
df[df["ciudad"].isin(["Quito", "Guayaquil", "Cuenca"])].reset_index(drop = True)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,nombre_clean
0,157646670,Sebastián Loor Romero,34.0,164.8,147.3,F,736.24,Cuenca,2024-04-28,Universidad,sebastian.loor.romero@yahoo.com,Sebastián Loor Romero
1,136450210,DIANA CEDEÑO VALENCIA,37.0,158.3,130.8,M,870.97,Cuenca,2024-07-21,Universidad,diana.cedeno.valencia@empresa.ec,Diana Cedeño Valencia
2,130988827,Fernanda Herrera Quintero,38.0,174.2,163.0,M,480.00,Cuenca,2025-07-07,Universidad,fernanda.herrera.quintero@yahoo.com,Fernanda Herrera Quintero
3,112860549,ALEJANDRA SILVA QUINTERO,38.0,157.6,143.6,M,766.22,Cuenca,2023-03-12,Universidad,NaN,Alejandra Silva Quintero
4,115694457001,Elena Tapia Espinoza,53.0,155.3,112.6,F,886.04,Cuenca,28/11/2023,Universidad,elena.tapia.espinoza@gmail.com,Elena Tapia Espinoza
...,...,...,...,...,...,...,...,...,...,...,...,...
33404,1714751730,Andrés Vera Solís,45.0,178.8,166.2,F,899.26,Quito,2023-10-24,Secundaria,NaN,Andrés Vera Solís
33405,1711139111,Gustavo Loor Sanchez,25.0,165.0,159.8,M,1858.30,Quito,NaN,Maestria,NaN,Gustavo Loor Sanchez
33406,1731070429001,gustavo quintero alvarado,35.0,175.3,174.0,M,1823.65,Quito,"Oct 29, 2024",Maestria,NaN,Gustavo Quintero Alvarado
33407,1719423194,vanessa romero mera,40.0,166.7,139.2,F,533.18,Quito,25/05/2025,Secundaria,vanessa.romero.mera@hotmail.com,Vanessa Romero Mera
33408,1731578199,MIGUEL CORNEJO ROMERO,29.0,168.8,118.2,F,811.75,Quito,04/06/2023,Universidad,miguel.cornejo.romero@empresa.ec,Miguel Cornejo Romero

In [42]:
#df.groupby("ciudad")["salario"].mean().reset_index()
#df.groupby("ciudad", as_index=False)["salario"].mean()

df.groupby(["ciudad", "sexo"])[["salario"]].mean().reset_index()
#df2.index

           ciudad sexo     salario
0          Ambato    F  766.494821
1          Ambato    M  765.020381
2          Cuenca    F  780.652789
3          Cuenca    M  787.521043
4      Esmeraldas    F  788.594719
5      Esmeraldas    M  763.738444
6       Guayaquil    F  804.028311
7       Guayaquil    M  794.201186
8          Ibarra    F  771.141362
9          Ibarra    M  767.219109
10           Loja    F  780.357144
11           Loja    M  757.017615
12        Machala    F  769.967242
13        Machala    M  765.973356
14          Manta    F  758.336760
15          Manta    M  768.268340
16     Portoviejo    F  784.228016
17     Portoviejo    M  762.840891
18        Quevedo    F  750.411602
19        Quevedo    M  761.798164
20          Quito    F  806.346618
21          Quito    M  796.725952
22       Riobamba    F  778.777255
23       Riobamba    M  778.511889
24        Salinas    F  750.979655
25        Salinas    M  790.581988
26  Santo Domingo    F  777.219737
27  Santo Domingo    M  803.316725

In [46]:
df.head()

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,nombre_clean
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.00,Ambato,28/03/2023,Secundaria,NaN,Paola Mera Rodriguez
1,1829202652,isabela molina silva,39.0,167.8,166.2,M,480.00,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,Isabela Molina Silva
2,1801036961,Fernanda Reyes Benítez,31.0,177.4,195.7,M,605.28,Ambato,"Apr 05, 2025",Secundaria,NaN,Fernanda Reyes Benítez
3,1823588783,gustavo molina mera,39.0,169.4,166.7,F,826.56,Ambato,06/03/2025,Secundaria,NaN,Gustavo Molina Mera
4,1816160012001,Sebastián Torres Cruz,28.0,179.4,183.7,M,1090.22,Ambato,2024-07-12,Universidad,sebastian.torres.cruz@hotmail.com,Sebastián Torres Cruz

In [49]:
df["fecha_registro"] = pd.to_datetime( df["fecha_registro"], format='mixed' )

---
### Preguntas propuestas por estudiantes:

Mayi contreras:
¿En que ciudades se obtienen mayores salarios en promedio?

In [69]:
#df.sort_values(["ciudad", "peso_lb"], ascending=[False, False])

In [61]:
df.groupby("ciudad")["salario"].mean().reset_index().sort_values("salario", ascending=False)

           ciudad     salario
10          Quito  801.364731
3       Guayaquil  798.954760
13  Santo Domingo  790.094251
1          Cuenca  784.227499
11       Riobamba  778.633814
2      Esmeraldas  775.512469
8      Portoviejo  772.792124
12        Salinas  770.704663
4          Ibarra  769.176427
6         Machala  767.999101
5            Loja  767.799406
0          Ambato  765.733728
7           Manta  763.442809
9         Quevedo  756.416021

Fanny Cisneros: Cual es el salario promedio por cada nnivel de educacion.  
Samantha Mazzini: ¿Existe una relación entre el nivel de educación y el salario promedio?

In [77]:
df.groupby(['nivel_educacion'], as_index=False)['salario'].mean()\
    .round(2)\
    .sort_values('salario', ascending=False)\
    .reset_index(drop=True)

  nivel_educacion  salario
0        Maestria  1023.20
1     Universidad   826.19
2         Tecnico   746.18
3      Secundaria   704.58
4        Primaria   674.49

In [74]:
salProm = df.groupby(['nivel_educacion'], as_index=False)['salario'].mean().round(2)
salProm = salProm.sort_values('salario', ascending=False).reset_index(drop=True)
salProm

  nivel_educacion  salario
0        Maestria  1023.20
1     Universidad   826.19
2         Tecnico   746.18
3      Secundaria   704.58
4        Primaria   674.49

Steven Espinosa: ¿La altura en centímetro de los hombres es mayor que las mujeres?

In [79]:
df.groupby("sexo")["altura_cm"].mean().round(2)

sexo
F    164.98
M    176.04
Name: altura_cm, dtype: float64

Fernando Espinoza: Porcentaje de hombres y porcentaje de mujeres en Quito

In [83]:
(df[(df["ciudad"]=="Quito")]["sexo"].value_counts(normalize = True)*100).round(2)

sexo
M    51.78
F    48.22
Name: proportion, dtype: float64

David Jurado: ¿Hay equidad de sexo para cada una de las ciudades?

In [91]:
df.groupby("ciudad")["sexo"].value_counts(normalize= True).unstack()

sexo                  F         M
ciudad
Ambato         0.483809  0.516191
Cuenca         0.479531  0.520469
Esmeraldas     0.473684  0.526316
Guayaquil      0.483720  0.516280
Ibarra         0.499029  0.500971
Loja           0.461954  0.538046
Machala        0.507212  0.492788
Manta          0.485877  0.514123
Portoviejo     0.465291  0.534709
Quevedo        0.472675  0.527325
Quito          0.482168  0.517832
Riobamba       0.459459  0.540541
Salinas        0.501923  0.498077
Santo Domingo  0.506667  0.493333

In [87]:
df2 = df.groupby(["ciudad", "sexo"]).size().unstack()
df2["Total"] = df2["F"] + df2["M"]
df2["F"] = df2["F"]/df2["Total"]
df2["M"] = df2["M"]/df2["Total"]
df2

sexo                  F         M  Total
ciudad
Ambato         0.483809  0.516191   2594
Cuenca         0.479531  0.520469   7426
Esmeraldas     0.473684  0.526316   1539
Guayaquil      0.483720  0.516280  14711
Ibarra         0.499029  0.500971   1545
Loja           0.461954  0.538046   2221
Machala        0.507212  0.492788   2080
Manta          0.485877  0.514123   3151
Portoviejo     0.465291  0.534709   2665
Quevedo        0.472675  0.527325   1043
Quito          0.482168  0.517832  11272
Riobamba       0.459459  0.540541   1332
Salinas        0.501923  0.498077   1040
Santo Domingo  0.506667  0.493333   1275


Vanessa Loor: ¿Cómo se distribuyen los niveles de educación por ciudad?

Joffre Jimenez: ¿La distribución de niveles educativos es diferente entre hombres y mujeres?

Profesor: ¿Cual es la Distribución de nivel académico por ciudad? ¿Qué ciudad tiene un mayor porcentaje de personas con Maestría?