# Clase 1 — Semana 1: Introducción a Pandas 1  
**Autor:** Robert Moreno  

> **Objetivo:** Familiarizarse con la lectura de datos y las primeras exploraciones con *Pandas* (head, tail, sample, shape, info) y con selección básica usando `loc` / `iloc`.

## 0) Preparación

En esta clase trabajaremos con un archivo llamado **`personas.csv`**.

**Hints:**
- Guarda `personas.csv` en la **misma carpeta** que este notebook antes de ejecutar el código.
- Si usas **Google Colab**, primero sube el archivo (menú *Files* → *Upload*) o monta tu Drive.
- Si al leer el CSV notas que las columnas no se separan bien, es posible que el separador **no sea coma**. En ese caso usa el parámetro `sep`, por ejemplo: `sep=';'` o `sep='\t'`.

## 1) Leer el dataset

**Ejercicio 1:** Lee el archivo **`personas.csv`** y guárdalo en una variable llamada **`df`**.  
Luego muéstralo con **`df.head()`**.

**Hints:**
- Usa `pd.read_csv("personas.csv")`.
- Si el separador no es coma, usa `sep=...` (por ejemplo `sep=";"`).

In [3]:
# Tu solución aquí
import pandas as pd

df = pd.read_csv("personas.csv", sep = "|")
df.head()

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.00,Ambato,28/03/2023,Secundaria,NaN
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.00,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com
2,1801036961,Fernanda Reyes Benítez,31.0,177.4,195.7,m,605.28,Ambato,"Apr 05, 2025",Secundaria,NaN
3,1823588783,gustavo molina mera,39.0,169.4,166.7,F,826.56,Ambato,06/03/2025,Secundaria,NaN
4,1816160012001,Sebastián Torres Cruz,28.0,179.4,183.7,m,1090.22,Ambato,2024-07-12,Universidad,sebastian.torres.cruz@hotmail.com

## 2) Ver las últimas filas con `tail()`

**Ejercicio 2:** Ejecuta `df.tail()`.

📌 `tail()` muestra las **últimas filas** del DataFrame (por defecto 5).  
Sirve para verificar cómo “terminan” los datos (a veces hay filas raras o incompletas al final).

In [16]:
# Tu solución aquí
df.tail(5)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email
55102,2327253361,JAVIER BRAVO VALENCIA,32.0,169.5,183.2,m,480.00,Santo Domingo,26/09/2024,Secundaria,NaN
55103,2328223645001,Jose Moreno Loor,44.0,179.9,204.9,M,1001.04,Santo Domingo,22/12/2025,Universidad,jose.moreno.loor@empresa.ec
55104,2344938291001,Paola Valencia Villamar,29.0,173.8,172.3,f,704.34,Santo Domingo,2025-11-13,Secundaria,paola.valencia.villamar@outlook.com
55105,2336761735,Ricardo Romero Chávez,30.0,180.7,193.5,m,794.08,Santo Domingo,"Dec 20, 2025",Universidad,RICARDO.ROMERO.CHAVEZ@YAHOO.COM
55106,2343577132,Andrés Silva García,41.0,162.1,149.0,f,720.60,Santo Domingo,09/12/2024,Secundaria,andres.silva.garcia@outlook.com

## 3) Tomar una muestra aleatoria con `sample()`

**Ejercicio 3:** Ejecuta `df.sample(7)`.

📌 `sample(n)` trae **n filas aleatorias** del DataFrame.  
Útil para explorar datos sin sesgo de “solo inicio/fin”.

In [44]:
# Tu solución aquí
df.sample(3)
#df.sample(frac= 0.05)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email
22218,947889994001,fernanda tapia espinoza,34.0,171.2,163.3,f,776.85,Guayaquil,2025-02-08,Secundaria,fernanda.tapia.espinoza@hotmail.com
580,1826921676,Lucía Flores Zambrano,39.0,163.7,132.9,f,780.07,Ambato,17/12/2025,Universidad,lucia.flores.zambrano@empresa.ec
8670,112593116001,Esteban Bravo Arévalo,28.0,170.9,151.0,F,669.71,Cuenca,2025-02-14,Universidad,esteban.bravo.arevalo@outlook.com

## 4) Dimensiones del DataFrame con `shape`

**Ejercicio 4:** Ejecuta `df.shape`.

📌 `shape` devuelve una tupla: **(filas, columnas)**.

In [45]:
# Tu solución aquí
df.shape

(55107, 11)

## 5) Resumen de tipos y nulos con `info()`

**Ejercicio 5:** Ejecuta `df.info()`.

📌 `info()` muestra:
- Número de filas
- Nombres de columnas
- Tipos de datos (`dtype`)
- Cuántos valores **no nulos** tiene cada columna

✅ Tarea: Identifica **qué columnas tienen nulos** (puedes escribirlo como comentario).

In [46]:
# Tu solución aquí
df.info()

# Columnas con nulos (comentario):

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55107 entries, 0 to 55106
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   identificacion   55107 non-null  int64
 1   nombre           55107 non-null  object
 2   edad             53537 non-null  float64
 3   altura_cm        55107 non-null  float64
 4   peso_lb          55107 non-null  float64
 5   sexo             55107 non-null  object
 6   salario          55107 non-null  float64
 7   ciudad           55107 non-null  object
 8   fecha_registro   51831 non-null  object
 9   nivel_educacion  55107 non-null  object
 10  email            32050 non-null  object
dtypes: float64(4), int64(1), object(6)
memory usage: 4.6+ MB

## 6) Seleccionar una columna y guardarla en una variable

**Ejercicio 6:** Guarda la columna **`edad`** en una variable llamada **`edades`**.

📌 Recuerda que una columna es un `Series`: `df["columna"]`.

In [56]:
# Tu solución aquí
edades = df["edad"]

In [68]:
#df[["altura_cm", "edad" ]]

## 7) Selección de datos con `iloc` y `loc`

**Idea clave:**
- `iloc` selecciona por **posición** (índices numéricos: 0, 1, 2, ...)
- `loc` selecciona por **etiqueta** (labels del índice y nombres de columnas)

En esta clase haremos **solo**:
1) Seleccionar **filas**  
2) Seleccionar **filas y columnas**

> Nota: Si tu DataFrame tiene índice 0..n-1, `loc` y `iloc` pueden verse similares, pero funcionan distinto.

### 7.1 `iloc` — Seleccionar solo filas (por posición)

**Ejercicio 7.1:** Obtén las filas en posiciones:
- 10 a 15 (incluyendo 10 Y 15)

**Hint:** En slicing de Python el extremo derecho **no se incluye**.

In [94]:
df.head()
#df.iloc[filas]
#df.iloc[[0,1,2]]
#df.iloc[10:101]
df.iloc[[0]]

#df.iloc[filas, columnas]
#df.iloc[3:8 , [1,2] ]
#df.iloc[: , [1,2] ]

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.0,Ambato,28/03/2023,Secundaria,NaN

In [97]:
df.iloc[2,3]

np.float64(177.4)

In [101]:
#df.head()
#df.iloc[2,5]

### 7.2 `iloc` — Seleccionar filas y columnas (por posición)

**Ejercicio 7.2:** Selecciona:
- Filas 0 a 4
- Solo las columnas en posiciones 0, 1, 2 (las primeras 3 columnas)

**Hint:** `df.iloc[filas, columnas]`

In [106]:
# Tu solución aquí
#df.iloc[0:5]
#df.iloc[ : , 0:3]

### 7.3 `loc` — Seleccionar solo filas (por etiqueta)

**Ejercicio 7.3:** Selecciona las filas con etiqueta:
- Desde 0 hasta 4 **incluyendo** 4

📌 Diferencia importante: en `loc` el slicing por etiquetas **sí incluye** el extremo derecho.

In [124]:
df.loc[0:10, "nombre": "ciudad"]

                        nombre  edad  altura_cm  peso_lb sexo  salario  ciudad
0         Paola Mera Rodriguez  31.0      166.4    141.8    F   480.00  Ambato
1         isabela molina silva  39.0      167.8    166.2    m   480.00  Ambato
2       Fernanda Reyes Benítez  31.0      177.4    195.7    m   605.28  Ambato
3          gustavo molina mera  39.0      169.4    166.7    F   826.56  Ambato
4        Sebastián Torres Cruz  28.0      179.4    183.7    m  1090.22  Ambato
5   Esteban  Villamar  Navarro  37.0      191.7    197.9    M  1003.85  Ambato
6      GABRIELA SILVA ESPINOZA  46.0      157.4    108.3    f   635.22  Ambato
7      Carmen Mendoza Valencia  53.0      183.0    187.5    m   480.00  Ambato
8    javier quintero villamar    NaN      169.5    146.7    m   480.00  Ambato
9      NATALIA FLORES ESPINOZA  28.0      179.6    157.7    m  1109.90  Ambato
10        David Loor Rodriguez  34.0      167.6    130.7    f  1168.12  Ambato

In [ ]:
# Tu solución aquí
#df.loc[1:5 , ["nombre", "edad"]]

                       nombre  edad
1        isabela molina silva  39.0
2      Fernanda Reyes Benítez  31.0
3         gustavo molina mera  39.0
4       Sebastián Torres Cruz  28.0
5  Esteban  Villamar  Navarro  37.0

### 7.4 `loc` — Seleccionar filas y columnas (por etiqueta)

**Ejercicio 7.4:** Selecciona filas 0 a 9 y las columnas:
- `"nombre"`, `"edad"`, `"salario"`

**Hint:** `df.loc[filas, ["col1","col2",...]]`

In [10]:
# Tu solución aquí

## 8) Crear la columna `altura_m`

**Ejercicio 8:** Crea una columna llamada **`altura_m`** convirtiendo `altura_cm` a metros.

**Hint:**  
- 1 metro = 100 centímetros  
- Fórmula: `altura_m = altura_cm / 100`

In [148]:
df["cohorte"] = "IV"
df.head(3)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,altura_m,cohorte,peso_kg,BMI
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.00,Ambato,28/03/2023,Secundaria,NaN,1.664,IV,64.319346,23.229239
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.00,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,1.678,IV,75.386990,26.773953
2,1801036961,Fernanda Reyes Benítez,31.0,177.4,195.7,m,605.28,Ambato,"Apr 05, 2025",Secundaria,NaN,1.774,IV,88.767954,28.206486

In [140]:
# Tu solución aquí
df["altura_m"] = df["altura_cm"]/100
df.head(2)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,altura_m,cohorte,peso_kg,BMI
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.0,Ambato,28/03/2023,Secundaria,NaN,1.664,IV,64.319346,0.000387
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.0,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,1.678,IV,75.386990,0.000449

## 9) Crear la columna `peso_kg`

**Ejercicio 9:** Crea una columna llamada **`peso_kg`** convirtiendo `peso_lb` (libras) a kilogramos.

**Hint:**  
- 1 lb ≈ 0.453592 kg  
- Fórmula: `peso_kg = peso_lb * 0.453592`

In [137]:
# Tu solución aquí
#df["peso_kg"] = df.loc[:, "peso_lb"] * 0.453592
df["peso_kg"] = df["peso_lb"] * 0.453592
df.head(2)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,altura_m,cohorte,peso_kg
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.0,Ambato,28/03/2023,Secundaria,NaN,166400.0,IV,64.319346
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.0,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,167800.0,IV,75.386990

## 10) Calcular `BMI` (Body Mass Index)

**¿Qué es el BMI?**  
El **Índice de Masa Corporal (BMI)** es una medida aproximada que relaciona peso y altura:

$$
BMI = \frac{peso\,(kg)}{altura\,(m)^2}
$$

**Referencia rápida (adultos):**
- **Sobrepeso**: BMI ≥ 25  
- **Obesidad**: BMI ≥ 30  

**Ejercicio 10:** Crea la columna **`BMI`** usando `peso_kg` y `altura_m`.

In [147]:
# Tu solución aquí
df['BMI'] = df["peso_kg"]/ (df["altura_m"] **2)
df.head(2)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,altura_m,cohorte,peso_kg,BMI
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.0,Ambato,28/03/2023,Secundaria,NaN,1.664,IV,64.319346,23.229239
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.0,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,1.678,IV,75.386990,26.773953

## 11) Crear la columna `tiene_sobrepeso`

**Ejercicio 11:** Crea una columna booleana llamada **`tiene_sobrepeso`** que sea:
- `True` si BMI ≥ 25  
- `False` si BMI < 25

**Hint:** Comparaciones vectorizadas: `df["BMI"] >= 25`

In [ ]:
# Tu solución aquí
df["tiene_sobrepeso"] = df["BMI"]>=25
df.head(2)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,altura_m,cohorte,peso_kg,BMI,tiene_sobrepeso
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.0,Ambato,28/03/2023,Secundaria,NaN,1.664,IV,64.319346,23.229239,False
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.0,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,1.678,IV,75.386990,26.773953,True

In [ ]:
#df[serie_boleana]
#df[mascara_booleana]

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,altura_m,cohorte,peso_kg,BMI,tiene_sobrepeso
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.00,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,1.678,IV,75.386990,26.773953,True
2,1801036961,Fernanda Reyes Benítez,31.0,177.4,195.7,m,605.28,Ambato,"Apr 05, 2025",Secundaria,NaN,1.774,IV,88.767954,28.206486,True
3,1823588783,gustavo molina mera,39.0,169.4,166.7,F,826.56,Ambato,06/03/2025,Secundaria,NaN,1.694,IV,75.613786,26.349609,True
4,1816160012001,Sebastián Torres Cruz,28.0,179.4,183.7,m,1090.22,Ambato,2024-07-12,Universidad,sebastian.torres.cruz@hotmail.com,1.794,IV,83.324850,25.889858,True
7,1833172982,Carmen Mendoza Valencia,53.0,183.0,187.5,m,480.00,Ambato,11/05/2024,Tecnico,NaN,1.830,IV,85.048500,25.395951,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55102,2327253361,JAVIER BRAVO VALENCIA,32.0,169.5,183.2,m,480.00,Santo Domingo,26/09/2024,Secundaria,NaN,1.695,IV,83.098054,28.923540,True
55103,2328223645001,Jose Moreno Loor,44.0,179.9,204.9,M,1001.04,Santo Domingo,22/12/2025,Universidad,jose.moreno.loor@empresa.ec,1.799,IV,92.941001,28.717393,True
55104,2344938291001,Paola Valencia Villamar,29.0,173.8,172.3,f,704.34,Santo Domingo,2025-11-13,Secundaria,paola.valencia.villamar@outlook.com,1.738,IV,78.153902,25.873258,True
55105,2336761735,Ricardo Romero Chávez,30.0,180.7,193.5,m,794.08,Santo Domingo,"Dec 20, 2025",Universidad,RICARDO.ROMERO.CHAVEZ@YAHOO.COM,1.807,IV,87.770052,26.880049,True
55106,2343577132,Andrés Silva García,41.0,162.1,149.0,f,720.60,Santo Domingo,09/12/2024,Secundaria,andres.silva.garcia@outlook.com,1.621,IV,67.585208,25.720868,True

## 12) Reflexión: Calidad de datos

**Ejercicio 12:** En base a lo observado en el dataset, escribe como comentarios `#`:

- ¿Qué problemas detectas que podrían afectar la calidad del análisis?

> Escribe tus respuestas en la celda de abajo (solo comentarios).

In [ ]:
# Escribe aquí tus observaciones (solo comentarios):
# 1)
# 2)
# 3)